### ISSUE TITLE
Installing jupyter-archive breaks right click context menu in Jupyterlab 4

### ISSUE THREAD

**Issue by wragge** [jupyterlab-contrib/jupyter-archive#119]
## Description

After installing jupyter-archive, if I right click on items in the Jupyter Lab file browser  the context menu doesn't appear as expected. In the Javascript console the following error is reported: `TypeError: Path must be a string. Received undefined.`

Initially reported here: jupyterlab/jupyterlab/issues/14948

## Context

- Operating System and version: Pop!_OS 22.04 LTS
- Browser and version: Firefox 116.0 (64-bit)
-  JupyterLab version: 4.0.4

**Comment by fcollonval** [comment]
Thanks for reporting the bug @wragge

**Comment by underlines** [comment]
sorry for hijacking this issue. runpod.io doesn't allow to uninstall or disable the extension and it completely breaks the whole right click menu on runpod.io. Is there a simple way in the browser's javascript console to temporarily disable the extension messing with the default menu? the whole file browser becomes unusable due to this bug.

**Comment by fcollonval** [comment]
The enable/disable feature is a server side config. There is no way to fix it simply. I would reach for the Webservice you mention to request updating the package.

**Comment by wyliefoxxx** [comment]
@underlines I was worried when I saw your comment, but was able to fix the issue on runpod simply by uninstalling jupyter archive via the jupyter command console and refreshing the page

pip uninstall jupyter-archive
